### PR TITLE
Update localization.ru.lua

### PR DESCRIPTION
**Pull request by Hollicsh**
Full translation.

### CODE REVIEW

**Comment by MysticalOS** [comment]
Same question as cataclysm. Misc translations that are used for phase triggers, are they from running raids yourself and grabbing blizzards exact phrases?

**Comment by QartemisT** [comment]
Any updates on this? @Hollicsh

**Comment by Hollicsh** [comment]
I need some more time to figure out these details.
I'll let you know within a day or two.

**Comment by Hollicsh** [comment]
Ready.

**Pull request merged**
